//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.01 at 12:18:02 PM CEST 
//
/**
 * This module is about role management and attribute certificates
 * <p>
 * This module provides attribute certificates management
 * </p>
 *
 * @since 1.0
 * @author pascal.jakobi@gmail.com
 * @version 0.1
 */
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.xmlspif.org/spif", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlspif.spif;
